
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        namespace: default 
  template:
    metadata:
      name: '{{cluster}}-applications'
      labels:
        general: '{{cluster}}'
        all: 'argocd'
    spec:
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://github.com/SelfOrganizedCompany/argocd-application-sets
        targetRevision: HEAD
        path: .
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        retry:
          limit: 2
          backoff: 
            duration: 5s
            factor: 2
            maxDuration: 3m0s
